os: linux
dist: xenial
language: node_js
node_js: 14

branches:
  only:
  - master

install:
- yarn

script:
- yarn build

cache: yarn

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: ${GITHUB_ACCESS_TOKEN}
    local_dir: dist
    on:
      branch: master
