title: Docker Workshop
description: Docker 工作坊
base: /docker-workshop/
dest: dist
themeConfig:
  sidebar:
    - title: Exercises
      children:
        - /docs/exercises/exercises-01-hello-docker
        - /docs/exercises/exercises-02-run-first-container
        - /docs/exercises/exercises-03-port-forwarding
        - /docs/exercises/exercises-04-run-command
        - /docs/exercises/exercises-05-volume-mapping
        - /docs/exercises/exercises-06-using-docker-instead-install-tools
        - /docs/exercises/exercises-11-environment
        - /docs/exercises/exercises-12-link-container
        - /docs/exercises/exercises-13-persistent-image
        - /docs/exercises/exercises-14-persistent-container-filesystem
        - /docs/exercises/exercises-15-volume-advanced
        - /docs/exercises/exercises-16-backup-database
    - /docs/command-tricks
  repo: 104corp/docker-workshop
  repoLabel: GitHub
  editLinks: true
  editLinkText: 編輯這個頁面
