title: Docker Workshop
description: Docker 工作坊
base: /docker-workshop/
dest: dist
themeConfig:
  sidebar:
    - title: Exercises
      children:
        - /docs/exercises/exercises-01-hello-docker
        - /docs/exercises/exercises-02-run-first-container
        - /docs/exercises/exercises-03-port-forwording
        - /docs/exercises/exercises-04-run-command
  repo: 104corp/docker-workshop
  repoLabel: GitHub
  editLinks: true
  editLinkText: 編輯這個頁面
